<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="All Pet Store Tests" duration-ms="25514" started-at="2020-09-16T23:19:45 CEST" finished-at="2020-09-16T23:20:10 CEST">
    <groups>
    </groups>
    <test name="Negative Login Tests" duration-ms="25514" started-at="2020-09-16T23:19:45 CEST" finished-at="2020-09-16T23:20:10 CEST">
      <class name="framework.tests.FailedLoginTests">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="beforeClass" is-config="true" duration-ms="107" started-at="2020-09-16T23:19:45 CEST" finished-at="2020-09-16T23:19:45 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeTest(framework.driver.BrowserType)[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="beforeTest" is-config="true" duration-ms="9010" started-at="2020-09-16T23:19:45 CEST" finished-at="2020-09-16T23:19:54 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[FIREFOX]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="asUserTryToLogInWithIncorrectLoginAndPassword()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="asUserTryToLogInWithIncorrectLoginAndPassword" duration-ms="999" retried="true" started-at="2020-09-16T23:19:54 CEST" finished-at="2020-09-16T23:19:55 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!
at framework.page.objects.LoginPage.assertThatWarningIsDisplayed(LoginPage.java:71)
at framework.tests.FailedLoginTests.asUserTryToLogInWithIncorrectLoginAndPassword(FailedLoginTests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="afterTest" is-config="true" duration-ms="736" started-at="2020-09-16T23:19:55 CEST" finished-at="2020-09-16T23:19:56 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest(framework.driver.BrowserType)[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="beforeTest" is-config="true" duration-ms="5382" started-at="2020-09-16T23:19:56 CEST" finished-at="2020-09-16T23:20:01 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[FIREFOX]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="asUserTryToLogInWithIncorrectLoginAndPassword()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="asUserTryToLogInWithIncorrectLoginAndPassword" duration-ms="872" retried="true" started-at="2020-09-16T23:20:01 CEST" finished-at="2020-09-16T23:20:02 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!
at framework.page.objects.LoginPage.assertThatWarningIsDisplayed(LoginPage.java:71)
at framework.tests.FailedLoginTests.asUserTryToLogInWithIncorrectLoginAndPassword(FailedLoginTests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="afterTest" is-config="true" duration-ms="776" started-at="2020-09-16T23:20:02 CEST" finished-at="2020-09-16T23:20:03 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="beforeTest(framework.driver.BrowserType)[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="beforeTest" is-config="true" duration-ms="5460" started-at="2020-09-16T23:20:03 CEST" finished-at="2020-09-16T23:20:08 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[FIREFOX]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="asUserTryToLogInWithIncorrectLoginAndPassword()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="asUserTryToLogInWithIncorrectLoginAndPassword" duration-ms="909" started-at="2020-09-16T23:20:08 CEST" finished-at="2020-09-16T23:20:09 CEST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!
at framework.page.objects.LoginPage.assertThatWarningIsDisplayed(LoginPage.java:71)
at framework.tests.FailedLoginTests.asUserTryToLogInWithIncorrectLoginAndPassword(FailedLoginTests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:framework.tests.FailedLoginTests@27b2faa6]" name="afterTest" is-config="true" duration-ms="783" started-at="2020-09-16T23:20:10 CEST" finished-at="2020-09-16T23:20:10 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- framework.tests.FailedLoginTests -->
    </test> <!-- Negative Login Tests -->
  </suite> <!-- All Pet Store Tests -->
</testng-results>
