<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="c0dexter-HP-EliteBook-8540w" name="framework.tests.FailedLoginTests" tests="3" failures="1" timestamp="2020-09-16T23:20:10 CEST" time="24.927" errors="0">
  <testcase name="asUserTryToLogInWithIncorrectLoginAndPassword" time="10.695" classname="framework.tests.FailedLoginTests">
    <failure type="java.lang.AssertionError" message="Element text was: &quot;&lt;Invalid username or password. Signon failed.&gt;&quot;, but expecting to be: &quot;&lt;Invalid username or password. Signon failed. 222222&gt;&quot;!">
      <![CDATA[java.lang.AssertionError: Element text was: "<Invalid username or password. Signon failed.>", but expecting to be: "<Invalid username or password. Signon failed. 222222>"!
at framework.page.objects.LoginPage.assertThatWarningIsDisplayed(LoginPage.java:71)
at framework.tests.FailedLoginTests.asUserTryToLogInWithIncorrectLoginAndPassword(FailedLoginTests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:443)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
  <testcase name="asUserTryToLogInWithIncorrectLoginAndPassword" time="7.242" classname="framework.tests.FailedLoginTests">
    <skipped/>
  </testcase> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
  <testcase name="asUserTryToLogInWithIncorrectLoginAndPassword" time="6.990" classname="framework.tests.FailedLoginTests">
    <skipped/>
  </testcase> <!-- asUserTryToLogInWithIncorrectLoginAndPassword -->
</testsuite> <!-- framework.tests.FailedLoginTests -->
